#!/usr/bin/python2.7
# -*- coding: utf-8 -*-
from __future__ import (
    absolute_import, division, print_function, unicode_literals
)
from io import open
# let's just pretend that this is Python 3


from time import sleep, time
from datetime import date
from requests import Session
import json
import shutil
import os

URL = "https://www.chaosdorf.de/~ytvwld/freitagsfoo.json"
LOADING_DATA = {
    "hosts": ["..."],
    "date": str(date.today()),
    "talks": [{
        "title": "...",
        "description": "...",
        "persons": [],
    }]
}
FILENAME = "freitagsfoo.json"
FOLDERS_TO_WRITE = (".", "talks_screen", "title_screen", "next_screen")


def save_bytes(content):
    curr_time = time()
    filename = "freitagsfoo-%s.json" % str(curr_time)
    f = open(filename, "wb")
    f.write(content)
    f.close()
    for folder in FOLDERS_TO_WRITE:
        shutil.copy(filename, "{}/{}".format(folder, FILENAME))
    os.remove(filename)


save_bytes(json.dumps(LOADING_DATA))

session = Session()
while True:
    r = session.get(URL)
    save_bytes(r.content)
    sleep(60)
